// User reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';
export const MARK_ONE_NOTIFICATION_READ = 'MARK_ONE_NOTIFICATION_READ';
export const FIND_FOLLOWER = 'FIND_FOLLOWER';
export const FIND_FOLLOWED = 'FIND_FOLLOWED';
export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';
export const FOLLOW_BACK = 'FOLLOW_BACK';
export const REVOKE_FOLLOW_BACK = 'REVOKE_FOLLOW_BACK';
export const CLEAR_FOLLOWER = 'CLEAR_FOLLOWER';
export const SHOW_FOLLOW_ALERT = 'SHOW_FOLLOW_ALERT';
export const HIDE_FOLLOW_ALERT = 'HIDE_FOLLOW_ALERT';
export const SHOW_UNFOLLOW_ALERT = 'SHOW_UNFOLLOW_ALERT';
export const HIDE_UNFOLLOW_ALERT = 'HIDE_UNFOLLOW_ALERT';
export const SHOW_FOLLOWBACK_ALERT = 'SHOW_FOLLOWBACK_ALERT';
export const HIDE_FOLLOWBACK_ALERT = 'HIDE_FOLLOWBACK_ALERT';
export const SHOW_REVOKEFOLLOW_ALERT = 'HIDE_UNFOLLOW_ALERT';
export const HIDE_REVOKEFOLLOW_ALERT = 'HIDE_REVOKEFOLLOW_ALERT';

// UI reducer typesÍ
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';

// Data reducer types
export const LOADING_ARTICLES = 'LOADING_ARTICLES';
export const STOP_LOADING_ARTICLES = 'STOP_LOADING_ARTICLES';
export const SET_ARTICLES = 'SET_ARTICLES';
export const SET_ARTICLE = 'SET_ARTICLE';
export const LIKE_ARTICLE = 'LIKE_ARTICLE';
export const UNLIKE_ARTICLE = 'UNLIKE_ARTICLE';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const POST_ARTICLE = 'POST_ARTICLE';
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';
export const CLEAR_ARTICLE = 'CLEAR_ARTICLE';
export const LOADING_PROFILE_DATA = 'LOADING_PROFILE_DATA';
export const SET_PROFILE = 'SET_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const SET_TRACKS = 'SET_TRACKS';
export const CLEAR_TRACKS = 'CLEAR_TRACKS';
export const LOADING_TRACKS = 'LOADING_TRACKS';
export const STOP_LOADING_TRACKS = 'STOP_LOADING_TRACKS';
export const LOADING_PROFILE = 'LOADING_PROFILE';
export const STOP_LOADING_PROFILE = 'STOP_LOADING_PROFILE';
export const FILTER_BY_TAG = 'FILTER_BY_TAG';
export const LOADING_TAG_ARTICLE = 'LOADING_TAG_ARTICLE';
export const STOP_LOADING_TAG_ARTICLE = 'STOP_LOADING_TAG_ARTICLE';