// User reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';
export const MARK_ONE_NOTIFICATION_READ = 'MARK_ONE_NOTIFICATION_READ';

// UI reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';

// Data reducer types
export const LOADING_ARTICLES = 'LOADING_ARTICLES';
export const STOP_LOADING_ARTICLES = 'STOP_LOADING_ARTICLES';
export const SET_ARTICLES = 'SET_ARTICLES';
export const SET_ARTICLE = 'SET_ARTICLE';
export const LIKE_ARTICLE = 'LIKE_ARTICLE';
export const UNLIKE_ARTICLE = 'UNLIKE_ARTICLE';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const POST_ARTICLE = 'POST_ARTICLE';
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';
export const CLEAR_ARTICLE = 'CLEAR_ARTICLE';
export const LOADING_PROFILE_DATA = 'LOADING_PROFILE_DATA';
export const SET_PROFILE = 'SET_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const SET_TRACKS = 'SET_TRACKS';
export const CLEAR_TRACKS = 'CLEAR_TRACKS';
export const LOADING_TRACKS = 'LOADING_TRACKS';
export const STOP_LOADING_TRACKS = 'STOP_LOADING_TRACKS';
export const LOADING_PROFILE = 'LOADING_PROFILE';
export const STOP_LOADING_PROFILE = 'STOP_LOADING_PROFILE';
