module.exports = {
  DEBUG: true,
  IS_MOCK_ENABLED: false,
  API_BASE_DEV: 'http://localhost:5000/socialape-d8699/asia-east2/api',
  API_BASE_PROD: 'https://asia-east2-socialape-d8699.cloudfunctions.net/api',
  SCREAMS_URL: 'https://asia-east2-socialape-d8699.cloudfunctions.net/api/screams',
  SCREAMS_PAGE_SIZE: 4,
  SOUNDCLOUD_URL: 'https://api.soundcloud.com',
  SOUNDCLOUD_USER_ID: '94957189',
  SOUNDCLOUD_CLIENT_ID: 'caf73ef1e709f839664ab82bef40fa96',
  SOUNDCLOUD_PAGE_SIZE: 12,
  profile: {
    FEED_PAGE_SIZE: 4,
    LIKED_POST_PAGE_SIZE: 3,
    CONNECTIONS_PAGE_SIZE: 7
  },
  tags: [
    "android",
    "animation",
    "butt",
    "caramel",
    "cars",
    "clean",
    "coffee",
    "computerScience",
    "cookies",
    "cryptocurrency",
    "datascience",
    "dragons",
    "esports",
    "firebase",
    "flowers",
    "gaming",
    "happiness",
    "ios",
    "japan",
    "money",
    "pagination",
    "porsche",
    "pubg",
    "react",
    "singapore",
    "sugar",
    "sushi",
    "test",
    "tourism",
    "training",
    "usa"
  ],
};